// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zubt81qoHWLdGbZW45W8NkPkWw569oU',
    appId: '1:682314435499:web:2ebb946d7dc6a3e4a920ee',
    messagingSenderId: '682314435499',
    projectId: 'ecomerce-c91cb',
    authDomain: 'ecomerce-c91cb.firebaseapp.com',
    storageBucket: 'ecomerce-c91cb.firebasestorage.app',
    measurementId: 'G-EZYF3L9532',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCJLVYU68Ufdo2zfpgZ4q4w5kPx3_v5s',
    appId: '1:682314435499:android:d2a21d4cb7f68588a920ee',
    messagingSenderId: '682314435499',
    projectId: 'ecomerce-c91cb',
    storageBucket: 'ecomerce-c91cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV6rQWQqtK1IKDV2-8IXZXbyzAoH_CYuQ',
    appId: '1:682314435499:ios:d33a2bf3e4eec4f9a920ee',
    messagingSenderId: '682314435499',
    projectId: 'ecomerce-c91cb',
    storageBucket: 'ecomerce-c91cb.firebasestorage.app',
    iosBundleId: 'com.example.ecomerce',
  );
}
