// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWEW8YjqAfZfqxQ4FddvJjRLBC9vtds1k',
    appId: '1:413425250176:web:7a9411f342119befe25b65',
    messagingSenderId: '413425250176',
    projectId: 'ecomerce-1f0fe',
    authDomain: 'ecomerce-1f0fe.firebaseapp.com',
    storageBucket: 'ecomerce-1f0fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAePMh5UmEwN3Z_VNF-AEKmZA_MRgCpwvY',
    appId: '1:413425250176:android:bcf63eccc8454b16e25b65',
    messagingSenderId: '413425250176',
    projectId: 'ecomerce-1f0fe',
    storageBucket: 'ecomerce-1f0fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA571U3rCdaTqHZN07HwejG1HEnc91eAR8',
    appId: '1:413425250176:ios:cd590f4afd0996b0e25b65',
    messagingSenderId: '413425250176',
    projectId: 'ecomerce-1f0fe',
    storageBucket: 'ecomerce-1f0fe.firebasestorage.app',
    iosBundleId: 'com.example.ecomerce',
  );
}
